# Change these first
owner: teamfolia # Your GitHub organization or username, where this repository lives
repo: folia-status # The name of this repository

sites:
  - name: app.folia.com backend
    url: https://app-api-test.folia.com/server-info

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.folia.com
  # baseUrl: /folia-status
  # logoUrl: https://images.squarespace-cdn.com/content/v1/61153edec162a522b9892bba/b8169773-9d0d-437f-9ed3-7f63392569f3/Folia-Logo-Orange.png?format=1500w
  name: status.folia.com
  introTitle: "Let ideas flow like pen on pape"
  introMessage: This lists the status of the app.folia.com related services.
  navbar:
    - title: app.folia.com
      href: https://app.folia.com
  themeUrl: https://status.folia.com/folia-status/folia-theme.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: https://www.folia.com
