# Change these first
owner: teamfolia # Your GitHub organization or username, where this repository lives
repo: folia-status # The name of this repository

workflowSchedule:
  main: "*/5 * * * *"

sites:
  - name: app.folia.com API
    url: https://app-api-test.folia.com/server-info
    assignees: # Users to assign downtime issues (optional)
     - sudeepa14

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.folia.com
  # baseUrl: /folia-status
  logoUrl: https://images.squarespace-cdn.com/content/v1/61153edec162a522b9892bba/b8169773-9d0d-437f-9ed3-7f63392569f3/Folia-Logo-Orange.png?format=1500w
  name: status.folia.com
  introTitle: "Let ideas flow like pen on paper"
  introMessage: This lists the status of the app.folia.com related services.
  navbar:
    - title: app.folia.com
      href: https://app.folia.com
  themeUrl: https://status.folia.com/folia-theme.css
  update_template: false
  # js: |
  #   window.onload = function() {
  #     setTimeout(function() {
  #       // Select all sections with the header "Past Incidents"
  #       const pastIncidentsSections = document.querySelectorAll('section:has(h2.svelte-18y4uo2)');

  #       pastIncidentsSections.forEach((section) => {
  #         const articles = section.querySelectorAll('article.down.link');
  #         articles.forEach((article) => {
  #           const heading = article.querySelector('h4');
  #           if (heading && heading.textContent.trim().startsWith("test")) {
  #             article.remove(); // Remove the article if it starts with "test"
  #           }
  #         });
  #       });
  #     }, 50);
  #   };

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: https://www.folia.com
