name: Trigger Private Repo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  repository_dispatch:
    types:
      - trigger-private-repo-workflow # Event type triggered by Uptime CI

jobs:
  trigger-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Private Repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PRIVATE_REPO_PAT }}" \
            https://api.github.com/repos/teamfolia/test-automation/actions/workflows/loadProject.yml/dispatches \
            -d '{"ref":"main"}'
